name: munchkinhalfling/s-mutt
sourceType: git
source: git://github.com/munchkinhalfling/s-mutt.git
scripts:
  build:
    - bettermake build
  install:
    - prefix=/usr bettermake build
depends: [munchkinhalfling/bettermake]
bin:
  smutt: bin/smutt
  smutt.genconf: bin/smutt.genconf
